/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HelpCenterIndexImport } from './routes/help-center/index'
import { Route as HomeIndexImport } from './routes/(Home)/index'
import { Route as StockStockImport } from './routes/(Stock)/stock'
import { Route as RhRhImport } from './routes/(Rh)/rh'
import { Route as ResourcesRoomsImport } from './routes/(Resources)/rooms'
import { Route as ResourcesEquipmentsImport } from './routes/(Resources)/equipments'
import { Route as ResourcesAmbulanceImport } from './routes/(Resources)/ambulance'
import { Route as ReceptionistReceptionistImport } from './routes/(Receptionist)/receptionist'
import { Route as PharmacyPharmacyImport } from './routes/(Pharmacy)/pharmacy'
import { Route as NurseNurseImport } from './routes/(Nurse)/nurse'
import { Route as MonitoringMonitoringImport } from './routes/(Monitoring)/monitoring'
import { Route as MedicalRecordsMedicalRecordsImport } from './routes/(MedicalRecords)/medical-records'
import { Route as LaboratoryLaboratoryImport } from './routes/(Laboratory)/laboratory'
import { Route as FinancePaymentsImport } from './routes/(Finance)/payments'
import { Route as FinanceFinanceImport } from './routes/(Finance)/finance'
import { Route as DoctorDoctorImport } from './routes/(Doctor)/doctor'
import { Route as DashboardDashboardImport } from './routes/(Dashboard)/dashboard'
import { Route as CalendarCalendarImport } from './routes/(Calendar)/calendar'
import { Route as AuthRegisterImport } from './routes/(Auth)/register'
import { Route as AuthLoginImport } from './routes/(Auth)/login'
import { Route as AuthForgotPasswordImport } from './routes/(Auth)/forgot-password'
import { Route as AppointmentAppointmentImport } from './routes/(Appointment)/appointment'
import { Route as AccessTermsAndConditionsImport } from './routes/(Access)/terms-and-conditions'
import { Route as AccessReleaseAccessImport } from './routes/(Access)/release-access'
import { Route as AccessPrivacyPolicyImport } from './routes/(Access)/privacy-policy'
import { Route as AccessIntegrationsImport } from './routes/(Access)/integrations'
import { Route as AccessAuditsImport } from './routes/(Access)/audits'
import { Route as PatientsPatientsIndexImport } from './routes/(Patients)/patients/index'
import { Route as MedicalRecordsMedicalRecordsIdImport } from './routes/(MedicalRecords)/medical-records/$id'
import { Route as PatientsPatientsProfileIdIndexImport } from './routes/(Patients)/patients/profile/$id/index'

// Create Virtual Routes

const SettingsRouteLazyImport = createFileRoute('/settings')()
const ChatsRouteLazyImport = createFileRoute('/chats')()
const ChatsIndexLazyImport = createFileRoute('/chats/')()
const SettingsProfileLazyImport = createFileRoute('/settings/profile')()
const SettingsNotificationsLazyImport = createFileRoute(
  '/settings/notifications',
)()
const SettingsDisplayLazyImport = createFileRoute('/settings/display')()
const SettingsAppearanceLazyImport = createFileRoute('/settings/appearance')()
const SettingsAccountLazyImport = createFileRoute('/settings/account')()

// Create/Update Routes

const SettingsRouteLazyRoute = SettingsRouteLazyImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/settings/route.lazy').then((d) => d.Route),
)

const ChatsRouteLazyRoute = ChatsRouteLazyImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/chats/route.lazy').then((d) => d.Route))

const ChatsIndexLazyRoute = ChatsIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatsRouteLazyRoute,
} as any).lazy(() => import('./routes/chats/index.lazy').then((d) => d.Route))

const HelpCenterIndexRoute = HelpCenterIndexImport.update({
  id: '/help-center/',
  path: '/help-center/',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexRoute = HomeIndexImport.update({
  id: '/(Home)/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsProfileLazyRoute = SettingsProfileLazyImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/settings/profile.lazy').then((d) => d.Route),
)

const SettingsNotificationsLazyRoute = SettingsNotificationsLazyImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/settings/notifications.lazy').then((d) => d.Route),
)

const SettingsDisplayLazyRoute = SettingsDisplayLazyImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/settings/display.lazy').then((d) => d.Route),
)

const SettingsAppearanceLazyRoute = SettingsAppearanceLazyImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/settings/appearance.lazy').then((d) => d.Route),
)

const SettingsAccountLazyRoute = SettingsAccountLazyImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/settings/account.lazy').then((d) => d.Route),
)

const StockStockRoute = StockStockImport.update({
  id: '/(Stock)/stock',
  path: '/stock',
  getParentRoute: () => rootRoute,
} as any)

const RhRhRoute = RhRhImport.update({
  id: '/(Rh)/rh',
  path: '/rh',
  getParentRoute: () => rootRoute,
} as any)

const ResourcesRoomsRoute = ResourcesRoomsImport.update({
  id: '/(Resources)/rooms',
  path: '/rooms',
  getParentRoute: () => rootRoute,
} as any)

const ResourcesEquipmentsRoute = ResourcesEquipmentsImport.update({
  id: '/(Resources)/equipments',
  path: '/equipments',
  getParentRoute: () => rootRoute,
} as any)

const ResourcesAmbulanceRoute = ResourcesAmbulanceImport.update({
  id: '/(Resources)/ambulance',
  path: '/ambulance',
  getParentRoute: () => rootRoute,
} as any)

const ReceptionistReceptionistRoute = ReceptionistReceptionistImport.update({
  id: '/(Receptionist)/receptionist',
  path: '/receptionist',
  getParentRoute: () => rootRoute,
} as any)

const PharmacyPharmacyRoute = PharmacyPharmacyImport.update({
  id: '/(Pharmacy)/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRoute,
} as any)

const NurseNurseRoute = NurseNurseImport.update({
  id: '/(Nurse)/nurse',
  path: '/nurse',
  getParentRoute: () => rootRoute,
} as any)

const MonitoringMonitoringRoute = MonitoringMonitoringImport.update({
  id: '/(Monitoring)/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRoute,
} as any)

const MedicalRecordsMedicalRecordsRoute =
  MedicalRecordsMedicalRecordsImport.update({
    id: '/(MedicalRecords)/medical-records',
    path: '/medical-records',
    getParentRoute: () => rootRoute,
  } as any)

const LaboratoryLaboratoryRoute = LaboratoryLaboratoryImport.update({
  id: '/(Laboratory)/laboratory',
  path: '/laboratory',
  getParentRoute: () => rootRoute,
} as any)

const FinancePaymentsRoute = FinancePaymentsImport.update({
  id: '/(Finance)/payments',
  path: '/payments',
  getParentRoute: () => rootRoute,
} as any)

const FinanceFinanceRoute = FinanceFinanceImport.update({
  id: '/(Finance)/finance',
  path: '/finance',
  getParentRoute: () => rootRoute,
} as any)

const DoctorDoctorRoute = DoctorDoctorImport.update({
  id: '/(Doctor)/doctor',
  path: '/doctor',
  getParentRoute: () => rootRoute,
} as any)

const DashboardDashboardRoute = DashboardDashboardImport.update({
  id: '/(Dashboard)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const CalendarCalendarRoute = CalendarCalendarImport.update({
  id: '/(Calendar)/calendar',
  path: '/calendar',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/(Auth)/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/(Auth)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/(Auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const AppointmentAppointmentRoute = AppointmentAppointmentImport.update({
  id: '/(Appointment)/appointment',
  path: '/appointment',
  getParentRoute: () => rootRoute,
} as any)

const AccessTermsAndConditionsRoute = AccessTermsAndConditionsImport.update({
  id: '/(Access)/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRoute,
} as any)

const AccessReleaseAccessRoute = AccessReleaseAccessImport.update({
  id: '/(Access)/release-access',
  path: '/release-access',
  getParentRoute: () => rootRoute,
} as any)

const AccessPrivacyPolicyRoute = AccessPrivacyPolicyImport.update({
  id: '/(Access)/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRoute,
} as any)

const AccessIntegrationsRoute = AccessIntegrationsImport.update({
  id: '/(Access)/integrations',
  path: '/integrations',
  getParentRoute: () => rootRoute,
} as any)

const AccessAuditsRoute = AccessAuditsImport.update({
  id: '/(Access)/audits',
  path: '/audits',
  getParentRoute: () => rootRoute,
} as any)

const PatientsPatientsIndexRoute = PatientsPatientsIndexImport.update({
  id: '/(Patients)/patients/',
  path: '/patients/',
  getParentRoute: () => rootRoute,
} as any)

const MedicalRecordsMedicalRecordsIdRoute =
  MedicalRecordsMedicalRecordsIdImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => MedicalRecordsMedicalRecordsRoute,
  } as any)

const PatientsPatientsProfileIdIndexRoute =
  PatientsPatientsProfileIdIndexImport.update({
    id: '/(Patients)/patients/profile/$id/',
    path: '/patients/profile/$id/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/(Access)/audits': {
      id: '/(Access)/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AccessAuditsImport
      parentRoute: typeof rootRoute
    }
    '/(Access)/integrations': {
      id: '/(Access)/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AccessIntegrationsImport
      parentRoute: typeof rootRoute
    }
    '/(Access)/privacy-policy': {
      id: '/(Access)/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof AccessPrivacyPolicyImport
      parentRoute: typeof rootRoute
    }
    '/(Access)/release-access': {
      id: '/(Access)/release-access'
      path: '/release-access'
      fullPath: '/release-access'
      preLoaderRoute: typeof AccessReleaseAccessImport
      parentRoute: typeof rootRoute
    }
    '/(Access)/terms-and-conditions': {
      id: '/(Access)/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof AccessTermsAndConditionsImport
      parentRoute: typeof rootRoute
    }
    '/(Appointment)/appointment': {
      id: '/(Appointment)/appointment'
      path: '/appointment'
      fullPath: '/appointment'
      preLoaderRoute: typeof AppointmentAppointmentImport
      parentRoute: typeof rootRoute
    }
    '/(Auth)/forgot-password': {
      id: '/(Auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/(Auth)/login': {
      id: '/(Auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/(Auth)/register': {
      id: '/(Auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/(Calendar)/calendar': {
      id: '/(Calendar)/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarCalendarImport
      parentRoute: typeof rootRoute
    }
    '/(Dashboard)/dashboard': {
      id: '/(Dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardImport
      parentRoute: typeof rootRoute
    }
    '/(Doctor)/doctor': {
      id: '/(Doctor)/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorDoctorImport
      parentRoute: typeof rootRoute
    }
    '/(Finance)/finance': {
      id: '/(Finance)/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceFinanceImport
      parentRoute: typeof rootRoute
    }
    '/(Finance)/payments': {
      id: '/(Finance)/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof FinancePaymentsImport
      parentRoute: typeof rootRoute
    }
    '/(Laboratory)/laboratory': {
      id: '/(Laboratory)/laboratory'
      path: '/laboratory'
      fullPath: '/laboratory'
      preLoaderRoute: typeof LaboratoryLaboratoryImport
      parentRoute: typeof rootRoute
    }
    '/(MedicalRecords)/medical-records': {
      id: '/(MedicalRecords)/medical-records'
      path: '/medical-records'
      fullPath: '/medical-records'
      preLoaderRoute: typeof MedicalRecordsMedicalRecordsImport
      parentRoute: typeof rootRoute
    }
    '/(Monitoring)/monitoring': {
      id: '/(Monitoring)/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringMonitoringImport
      parentRoute: typeof rootRoute
    }
    '/(Nurse)/nurse': {
      id: '/(Nurse)/nurse'
      path: '/nurse'
      fullPath: '/nurse'
      preLoaderRoute: typeof NurseNurseImport
      parentRoute: typeof rootRoute
    }
    '/(Pharmacy)/pharmacy': {
      id: '/(Pharmacy)/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyPharmacyImport
      parentRoute: typeof rootRoute
    }
    '/(Receptionist)/receptionist': {
      id: '/(Receptionist)/receptionist'
      path: '/receptionist'
      fullPath: '/receptionist'
      preLoaderRoute: typeof ReceptionistReceptionistImport
      parentRoute: typeof rootRoute
    }
    '/(Resources)/ambulance': {
      id: '/(Resources)/ambulance'
      path: '/ambulance'
      fullPath: '/ambulance'
      preLoaderRoute: typeof ResourcesAmbulanceImport
      parentRoute: typeof rootRoute
    }
    '/(Resources)/equipments': {
      id: '/(Resources)/equipments'
      path: '/equipments'
      fullPath: '/equipments'
      preLoaderRoute: typeof ResourcesEquipmentsImport
      parentRoute: typeof rootRoute
    }
    '/(Resources)/rooms': {
      id: '/(Resources)/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof ResourcesRoomsImport
      parentRoute: typeof rootRoute
    }
    '/(Rh)/rh': {
      id: '/(Rh)/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof RhRhImport
      parentRoute: typeof rootRoute
    }
    '/(Stock)/stock': {
      id: '/(Stock)/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockStockImport
      parentRoute: typeof rootRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountLazyImport
      parentRoute: typeof SettingsRouteLazyImport
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceLazyImport
      parentRoute: typeof SettingsRouteLazyImport
    }
    '/settings/display': {
      id: '/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof SettingsDisplayLazyImport
      parentRoute: typeof SettingsRouteLazyImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsLazyImport
      parentRoute: typeof SettingsRouteLazyImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileLazyImport
      parentRoute: typeof SettingsRouteLazyImport
    }
    '/(Home)/': {
      id: '/(Home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof rootRoute
    }
    '/help-center/': {
      id: '/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof HelpCenterIndexImport
      parentRoute: typeof rootRoute
    }
    '/chats/': {
      id: '/chats/'
      path: '/'
      fullPath: '/chats/'
      preLoaderRoute: typeof ChatsIndexLazyImport
      parentRoute: typeof ChatsRouteLazyImport
    }
    '/(MedicalRecords)/medical-records/$id': {
      id: '/(MedicalRecords)/medical-records/$id'
      path: '/$id'
      fullPath: '/medical-records/$id'
      preLoaderRoute: typeof MedicalRecordsMedicalRecordsIdImport
      parentRoute: typeof MedicalRecordsMedicalRecordsImport
    }
    '/(Patients)/patients/': {
      id: '/(Patients)/patients/'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsPatientsIndexImport
      parentRoute: typeof rootRoute
    }
    '/(Patients)/patients/profile/$id/': {
      id: '/(Patients)/patients/profile/$id/'
      path: '/patients/profile/$id'
      fullPath: '/patients/profile/$id'
      preLoaderRoute: typeof PatientsPatientsProfileIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface ChatsRouteLazyRouteChildren {
  ChatsIndexLazyRoute: typeof ChatsIndexLazyRoute
}

const ChatsRouteLazyRouteChildren: ChatsRouteLazyRouteChildren = {
  ChatsIndexLazyRoute: ChatsIndexLazyRoute,
}

const ChatsRouteLazyRouteWithChildren = ChatsRouteLazyRoute._addFileChildren(
  ChatsRouteLazyRouteChildren,
)

interface SettingsRouteLazyRouteChildren {
  SettingsAccountLazyRoute: typeof SettingsAccountLazyRoute
  SettingsAppearanceLazyRoute: typeof SettingsAppearanceLazyRoute
  SettingsDisplayLazyRoute: typeof SettingsDisplayLazyRoute
  SettingsNotificationsLazyRoute: typeof SettingsNotificationsLazyRoute
  SettingsProfileLazyRoute: typeof SettingsProfileLazyRoute
}

const SettingsRouteLazyRouteChildren: SettingsRouteLazyRouteChildren = {
  SettingsAccountLazyRoute: SettingsAccountLazyRoute,
  SettingsAppearanceLazyRoute: SettingsAppearanceLazyRoute,
  SettingsDisplayLazyRoute: SettingsDisplayLazyRoute,
  SettingsNotificationsLazyRoute: SettingsNotificationsLazyRoute,
  SettingsProfileLazyRoute: SettingsProfileLazyRoute,
}

const SettingsRouteLazyRouteWithChildren =
  SettingsRouteLazyRoute._addFileChildren(SettingsRouteLazyRouteChildren)

interface MedicalRecordsMedicalRecordsRouteChildren {
  MedicalRecordsMedicalRecordsIdRoute: typeof MedicalRecordsMedicalRecordsIdRoute
}

const MedicalRecordsMedicalRecordsRouteChildren: MedicalRecordsMedicalRecordsRouteChildren =
  {
    MedicalRecordsMedicalRecordsIdRoute: MedicalRecordsMedicalRecordsIdRoute,
  }

const MedicalRecordsMedicalRecordsRouteWithChildren =
  MedicalRecordsMedicalRecordsRoute._addFileChildren(
    MedicalRecordsMedicalRecordsRouteChildren,
  )

export interface FileRoutesByFullPath {
  '/chats': typeof ChatsRouteLazyRouteWithChildren
  '/settings': typeof SettingsRouteLazyRouteWithChildren
  '/audits': typeof AccessAuditsRoute
  '/integrations': typeof AccessIntegrationsRoute
  '/privacy-policy': typeof AccessPrivacyPolicyRoute
  '/release-access': typeof AccessReleaseAccessRoute
  '/terms-and-conditions': typeof AccessTermsAndConditionsRoute
  '/appointment': typeof AppointmentAppointmentRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/calendar': typeof CalendarCalendarRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/doctor': typeof DoctorDoctorRoute
  '/finance': typeof FinanceFinanceRoute
  '/payments': typeof FinancePaymentsRoute
  '/laboratory': typeof LaboratoryLaboratoryRoute
  '/medical-records': typeof MedicalRecordsMedicalRecordsRouteWithChildren
  '/monitoring': typeof MonitoringMonitoringRoute
  '/nurse': typeof NurseNurseRoute
  '/pharmacy': typeof PharmacyPharmacyRoute
  '/receptionist': typeof ReceptionistReceptionistRoute
  '/ambulance': typeof ResourcesAmbulanceRoute
  '/equipments': typeof ResourcesEquipmentsRoute
  '/rooms': typeof ResourcesRoomsRoute
  '/rh': typeof RhRhRoute
  '/stock': typeof StockStockRoute
  '/settings/account': typeof SettingsAccountLazyRoute
  '/settings/appearance': typeof SettingsAppearanceLazyRoute
  '/settings/display': typeof SettingsDisplayLazyRoute
  '/settings/notifications': typeof SettingsNotificationsLazyRoute
  '/settings/profile': typeof SettingsProfileLazyRoute
  '/': typeof HomeIndexRoute
  '/help-center': typeof HelpCenterIndexRoute
  '/chats/': typeof ChatsIndexLazyRoute
  '/medical-records/$id': typeof MedicalRecordsMedicalRecordsIdRoute
  '/patients': typeof PatientsPatientsIndexRoute
  '/patients/profile/$id': typeof PatientsPatientsProfileIdIndexRoute
}

export interface FileRoutesByTo {
  '/settings': typeof SettingsRouteLazyRouteWithChildren
  '/audits': typeof AccessAuditsRoute
  '/integrations': typeof AccessIntegrationsRoute
  '/privacy-policy': typeof AccessPrivacyPolicyRoute
  '/release-access': typeof AccessReleaseAccessRoute
  '/terms-and-conditions': typeof AccessTermsAndConditionsRoute
  '/appointment': typeof AppointmentAppointmentRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/calendar': typeof CalendarCalendarRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/doctor': typeof DoctorDoctorRoute
  '/finance': typeof FinanceFinanceRoute
  '/payments': typeof FinancePaymentsRoute
  '/laboratory': typeof LaboratoryLaboratoryRoute
  '/medical-records': typeof MedicalRecordsMedicalRecordsRouteWithChildren
  '/monitoring': typeof MonitoringMonitoringRoute
  '/nurse': typeof NurseNurseRoute
  '/pharmacy': typeof PharmacyPharmacyRoute
  '/receptionist': typeof ReceptionistReceptionistRoute
  '/ambulance': typeof ResourcesAmbulanceRoute
  '/equipments': typeof ResourcesEquipmentsRoute
  '/rooms': typeof ResourcesRoomsRoute
  '/rh': typeof RhRhRoute
  '/stock': typeof StockStockRoute
  '/settings/account': typeof SettingsAccountLazyRoute
  '/settings/appearance': typeof SettingsAppearanceLazyRoute
  '/settings/display': typeof SettingsDisplayLazyRoute
  '/settings/notifications': typeof SettingsNotificationsLazyRoute
  '/settings/profile': typeof SettingsProfileLazyRoute
  '/': typeof HomeIndexRoute
  '/help-center': typeof HelpCenterIndexRoute
  '/chats': typeof ChatsIndexLazyRoute
  '/medical-records/$id': typeof MedicalRecordsMedicalRecordsIdRoute
  '/patients': typeof PatientsPatientsIndexRoute
  '/patients/profile/$id': typeof PatientsPatientsProfileIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/chats': typeof ChatsRouteLazyRouteWithChildren
  '/settings': typeof SettingsRouteLazyRouteWithChildren
  '/(Access)/audits': typeof AccessAuditsRoute
  '/(Access)/integrations': typeof AccessIntegrationsRoute
  '/(Access)/privacy-policy': typeof AccessPrivacyPolicyRoute
  '/(Access)/release-access': typeof AccessReleaseAccessRoute
  '/(Access)/terms-and-conditions': typeof AccessTermsAndConditionsRoute
  '/(Appointment)/appointment': typeof AppointmentAppointmentRoute
  '/(Auth)/forgot-password': typeof AuthForgotPasswordRoute
  '/(Auth)/login': typeof AuthLoginRoute
  '/(Auth)/register': typeof AuthRegisterRoute
  '/(Calendar)/calendar': typeof CalendarCalendarRoute
  '/(Dashboard)/dashboard': typeof DashboardDashboardRoute
  '/(Doctor)/doctor': typeof DoctorDoctorRoute
  '/(Finance)/finance': typeof FinanceFinanceRoute
  '/(Finance)/payments': typeof FinancePaymentsRoute
  '/(Laboratory)/laboratory': typeof LaboratoryLaboratoryRoute
  '/(MedicalRecords)/medical-records': typeof MedicalRecordsMedicalRecordsRouteWithChildren
  '/(Monitoring)/monitoring': typeof MonitoringMonitoringRoute
  '/(Nurse)/nurse': typeof NurseNurseRoute
  '/(Pharmacy)/pharmacy': typeof PharmacyPharmacyRoute
  '/(Receptionist)/receptionist': typeof ReceptionistReceptionistRoute
  '/(Resources)/ambulance': typeof ResourcesAmbulanceRoute
  '/(Resources)/equipments': typeof ResourcesEquipmentsRoute
  '/(Resources)/rooms': typeof ResourcesRoomsRoute
  '/(Rh)/rh': typeof RhRhRoute
  '/(Stock)/stock': typeof StockStockRoute
  '/settings/account': typeof SettingsAccountLazyRoute
  '/settings/appearance': typeof SettingsAppearanceLazyRoute
  '/settings/display': typeof SettingsDisplayLazyRoute
  '/settings/notifications': typeof SettingsNotificationsLazyRoute
  '/settings/profile': typeof SettingsProfileLazyRoute
  '/(Home)/': typeof HomeIndexRoute
  '/help-center/': typeof HelpCenterIndexRoute
  '/chats/': typeof ChatsIndexLazyRoute
  '/(MedicalRecords)/medical-records/$id': typeof MedicalRecordsMedicalRecordsIdRoute
  '/(Patients)/patients/': typeof PatientsPatientsIndexRoute
  '/(Patients)/patients/profile/$id/': typeof PatientsPatientsProfileIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/chats'
    | '/settings'
    | '/audits'
    | '/integrations'
    | '/privacy-policy'
    | '/release-access'
    | '/terms-and-conditions'
    | '/appointment'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/calendar'
    | '/dashboard'
    | '/doctor'
    | '/finance'
    | '/payments'
    | '/laboratory'
    | '/medical-records'
    | '/monitoring'
    | '/nurse'
    | '/pharmacy'
    | '/receptionist'
    | '/ambulance'
    | '/equipments'
    | '/rooms'
    | '/rh'
    | '/stock'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/profile'
    | '/'
    | '/help-center'
    | '/chats/'
    | '/medical-records/$id'
    | '/patients'
    | '/patients/profile/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/audits'
    | '/integrations'
    | '/privacy-policy'
    | '/release-access'
    | '/terms-and-conditions'
    | '/appointment'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/calendar'
    | '/dashboard'
    | '/doctor'
    | '/finance'
    | '/payments'
    | '/laboratory'
    | '/medical-records'
    | '/monitoring'
    | '/nurse'
    | '/pharmacy'
    | '/receptionist'
    | '/ambulance'
    | '/equipments'
    | '/rooms'
    | '/rh'
    | '/stock'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/profile'
    | '/'
    | '/help-center'
    | '/chats'
    | '/medical-records/$id'
    | '/patients'
    | '/patients/profile/$id'
  id:
    | '__root__'
    | '/chats'
    | '/settings'
    | '/(Access)/audits'
    | '/(Access)/integrations'
    | '/(Access)/privacy-policy'
    | '/(Access)/release-access'
    | '/(Access)/terms-and-conditions'
    | '/(Appointment)/appointment'
    | '/(Auth)/forgot-password'
    | '/(Auth)/login'
    | '/(Auth)/register'
    | '/(Calendar)/calendar'
    | '/(Dashboard)/dashboard'
    | '/(Doctor)/doctor'
    | '/(Finance)/finance'
    | '/(Finance)/payments'
    | '/(Laboratory)/laboratory'
    | '/(MedicalRecords)/medical-records'
    | '/(Monitoring)/monitoring'
    | '/(Nurse)/nurse'
    | '/(Pharmacy)/pharmacy'
    | '/(Receptionist)/receptionist'
    | '/(Resources)/ambulance'
    | '/(Resources)/equipments'
    | '/(Resources)/rooms'
    | '/(Rh)/rh'
    | '/(Stock)/stock'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/profile'
    | '/(Home)/'
    | '/help-center/'
    | '/chats/'
    | '/(MedicalRecords)/medical-records/$id'
    | '/(Patients)/patients/'
    | '/(Patients)/patients/profile/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ChatsRouteLazyRoute: typeof ChatsRouteLazyRouteWithChildren
  SettingsRouteLazyRoute: typeof SettingsRouteLazyRouteWithChildren
  AccessAuditsRoute: typeof AccessAuditsRoute
  AccessIntegrationsRoute: typeof AccessIntegrationsRoute
  AccessPrivacyPolicyRoute: typeof AccessPrivacyPolicyRoute
  AccessReleaseAccessRoute: typeof AccessReleaseAccessRoute
  AccessTermsAndConditionsRoute: typeof AccessTermsAndConditionsRoute
  AppointmentAppointmentRoute: typeof AppointmentAppointmentRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  CalendarCalendarRoute: typeof CalendarCalendarRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DoctorDoctorRoute: typeof DoctorDoctorRoute
  FinanceFinanceRoute: typeof FinanceFinanceRoute
  FinancePaymentsRoute: typeof FinancePaymentsRoute
  LaboratoryLaboratoryRoute: typeof LaboratoryLaboratoryRoute
  MedicalRecordsMedicalRecordsRoute: typeof MedicalRecordsMedicalRecordsRouteWithChildren
  MonitoringMonitoringRoute: typeof MonitoringMonitoringRoute
  NurseNurseRoute: typeof NurseNurseRoute
  PharmacyPharmacyRoute: typeof PharmacyPharmacyRoute
  ReceptionistReceptionistRoute: typeof ReceptionistReceptionistRoute
  ResourcesAmbulanceRoute: typeof ResourcesAmbulanceRoute
  ResourcesEquipmentsRoute: typeof ResourcesEquipmentsRoute
  ResourcesRoomsRoute: typeof ResourcesRoomsRoute
  RhRhRoute: typeof RhRhRoute
  StockStockRoute: typeof StockStockRoute
  HomeIndexRoute: typeof HomeIndexRoute
  HelpCenterIndexRoute: typeof HelpCenterIndexRoute
  PatientsPatientsIndexRoute: typeof PatientsPatientsIndexRoute
  PatientsPatientsProfileIdIndexRoute: typeof PatientsPatientsProfileIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  ChatsRouteLazyRoute: ChatsRouteLazyRouteWithChildren,
  SettingsRouteLazyRoute: SettingsRouteLazyRouteWithChildren,
  AccessAuditsRoute: AccessAuditsRoute,
  AccessIntegrationsRoute: AccessIntegrationsRoute,
  AccessPrivacyPolicyRoute: AccessPrivacyPolicyRoute,
  AccessReleaseAccessRoute: AccessReleaseAccessRoute,
  AccessTermsAndConditionsRoute: AccessTermsAndConditionsRoute,
  AppointmentAppointmentRoute: AppointmentAppointmentRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  CalendarCalendarRoute: CalendarCalendarRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DoctorDoctorRoute: DoctorDoctorRoute,
  FinanceFinanceRoute: FinanceFinanceRoute,
  FinancePaymentsRoute: FinancePaymentsRoute,
  LaboratoryLaboratoryRoute: LaboratoryLaboratoryRoute,
  MedicalRecordsMedicalRecordsRoute:
    MedicalRecordsMedicalRecordsRouteWithChildren,
  MonitoringMonitoringRoute: MonitoringMonitoringRoute,
  NurseNurseRoute: NurseNurseRoute,
  PharmacyPharmacyRoute: PharmacyPharmacyRoute,
  ReceptionistReceptionistRoute: ReceptionistReceptionistRoute,
  ResourcesAmbulanceRoute: ResourcesAmbulanceRoute,
  ResourcesEquipmentsRoute: ResourcesEquipmentsRoute,
  ResourcesRoomsRoute: ResourcesRoomsRoute,
  RhRhRoute: RhRhRoute,
  StockStockRoute: StockStockRoute,
  HomeIndexRoute: HomeIndexRoute,
  HelpCenterIndexRoute: HelpCenterIndexRoute,
  PatientsPatientsIndexRoute: PatientsPatientsIndexRoute,
  PatientsPatientsProfileIdIndexRoute: PatientsPatientsProfileIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/chats",
        "/settings",
        "/(Access)/audits",
        "/(Access)/integrations",
        "/(Access)/privacy-policy",
        "/(Access)/release-access",
        "/(Access)/terms-and-conditions",
        "/(Appointment)/appointment",
        "/(Auth)/forgot-password",
        "/(Auth)/login",
        "/(Auth)/register",
        "/(Calendar)/calendar",
        "/(Dashboard)/dashboard",
        "/(Doctor)/doctor",
        "/(Finance)/finance",
        "/(Finance)/payments",
        "/(Laboratory)/laboratory",
        "/(MedicalRecords)/medical-records",
        "/(Monitoring)/monitoring",
        "/(Nurse)/nurse",
        "/(Pharmacy)/pharmacy",
        "/(Receptionist)/receptionist",
        "/(Resources)/ambulance",
        "/(Resources)/equipments",
        "/(Resources)/rooms",
        "/(Rh)/rh",
        "/(Stock)/stock",
        "/(Home)/",
        "/help-center/",
        "/(Patients)/patients/",
        "/(Patients)/patients/profile/$id/"
      ]
    },
    "/chats": {
      "filePath": "chats/route.lazy.tsx",
      "children": [
        "/chats/"
      ]
    },
    "/settings": {
      "filePath": "settings/route.lazy.tsx",
      "children": [
        "/settings/account",
        "/settings/appearance",
        "/settings/display",
        "/settings/notifications",
        "/settings/profile"
      ]
    },
    "/(Access)/audits": {
      "filePath": "(Access)/audits.tsx"
    },
    "/(Access)/integrations": {
      "filePath": "(Access)/integrations.tsx"
    },
    "/(Access)/privacy-policy": {
      "filePath": "(Access)/privacy-policy.tsx"
    },
    "/(Access)/release-access": {
      "filePath": "(Access)/release-access.tsx"
    },
    "/(Access)/terms-and-conditions": {
      "filePath": "(Access)/terms-and-conditions.tsx"
    },
    "/(Appointment)/appointment": {
      "filePath": "(Appointment)/appointment.tsx"
    },
    "/(Auth)/forgot-password": {
      "filePath": "(Auth)/forgot-password.tsx"
    },
    "/(Auth)/login": {
      "filePath": "(Auth)/login.tsx"
    },
    "/(Auth)/register": {
      "filePath": "(Auth)/register.tsx"
    },
    "/(Calendar)/calendar": {
      "filePath": "(Calendar)/calendar.tsx"
    },
    "/(Dashboard)/dashboard": {
      "filePath": "(Dashboard)/dashboard.tsx"
    },
    "/(Doctor)/doctor": {
      "filePath": "(Doctor)/doctor.tsx"
    },
    "/(Finance)/finance": {
      "filePath": "(Finance)/finance.tsx"
    },
    "/(Finance)/payments": {
      "filePath": "(Finance)/payments.tsx"
    },
    "/(Laboratory)/laboratory": {
      "filePath": "(Laboratory)/laboratory.tsx"
    },
    "/(MedicalRecords)/medical-records": {
      "filePath": "(MedicalRecords)/medical-records.tsx",
      "children": [
        "/(MedicalRecords)/medical-records/$id"
      ]
    },
    "/(Monitoring)/monitoring": {
      "filePath": "(Monitoring)/monitoring.tsx"
    },
    "/(Nurse)/nurse": {
      "filePath": "(Nurse)/nurse.tsx"
    },
    "/(Pharmacy)/pharmacy": {
      "filePath": "(Pharmacy)/pharmacy.tsx"
    },
    "/(Receptionist)/receptionist": {
      "filePath": "(Receptionist)/receptionist.tsx"
    },
    "/(Resources)/ambulance": {
      "filePath": "(Resources)/ambulance.tsx"
    },
    "/(Resources)/equipments": {
      "filePath": "(Resources)/equipments.tsx"
    },
    "/(Resources)/rooms": {
      "filePath": "(Resources)/rooms.tsx"
    },
    "/(Rh)/rh": {
      "filePath": "(Rh)/rh.tsx"
    },
    "/(Stock)/stock": {
      "filePath": "(Stock)/stock.tsx"
    },
    "/settings/account": {
      "filePath": "settings/account.lazy.tsx",
      "parent": "/settings"
    },
    "/settings/appearance": {
      "filePath": "settings/appearance.lazy.tsx",
      "parent": "/settings"
    },
    "/settings/display": {
      "filePath": "settings/display.lazy.tsx",
      "parent": "/settings"
    },
    "/settings/notifications": {
      "filePath": "settings/notifications.lazy.tsx",
      "parent": "/settings"
    },
    "/settings/profile": {
      "filePath": "settings/profile.lazy.tsx",
      "parent": "/settings"
    },
    "/(Home)/": {
      "filePath": "(Home)/index.tsx"
    },
    "/help-center/": {
      "filePath": "help-center/index.tsx"
    },
    "/chats/": {
      "filePath": "chats/index.lazy.tsx",
      "parent": "/chats"
    },
    "/(MedicalRecords)/medical-records/$id": {
      "filePath": "(MedicalRecords)/medical-records/$id.tsx",
      "parent": "/(MedicalRecords)/medical-records"
    },
    "/(Patients)/patients/": {
      "filePath": "(Patients)/patients/index.tsx"
    },
    "/(Patients)/patients/profile/$id/": {
      "filePath": "(Patients)/patients/profile/$id/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
