/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeIndexImport } from './routes/(Home)/index'
import { Route as DashboardDashboardImport } from './routes/(Dashboard)/dashboard'
import { Route as AuthRegisterImport } from './routes/(Auth)/register'
import { Route as AuthLoginImport } from './routes/(Auth)/login'
import { Route as AuthForgotPasswordImport } from './routes/(Auth)/forgot-password'

// Create/Update Routes

const HomeIndexRoute = HomeIndexImport.update({
  id: '/(Home)/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardDashboardRoute = DashboardDashboardImport.update({
  id: '/(Dashboard)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/(Auth)/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/(Auth)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/(Auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(Auth)/forgot-password': {
      id: '/(Auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/(Auth)/login': {
      id: '/(Auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/(Auth)/register': {
      id: '/(Auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/(Dashboard)/dashboard': {
      id: '/(Dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardImport
      parentRoute: typeof rootRoute
    }
    '/(Home)/': {
      id: '/(Home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/': typeof HomeIndexRoute
}

export interface FileRoutesByTo {
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/': typeof HomeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(Auth)/forgot-password': typeof AuthForgotPasswordRoute
  '/(Auth)/login': typeof AuthLoginRoute
  '/(Auth)/register': typeof AuthRegisterRoute
  '/(Dashboard)/dashboard': typeof DashboardDashboardRoute
  '/(Home)/': typeof HomeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/forgot-password' | '/login' | '/register' | '/dashboard' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/forgot-password' | '/login' | '/register' | '/dashboard' | '/'
  id:
    | '__root__'
    | '/(Auth)/forgot-password'
    | '/(Auth)/login'
    | '/(Auth)/register'
    | '/(Dashboard)/dashboard'
    | '/(Home)/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  HomeIndexRoute: HomeIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(Auth)/forgot-password",
        "/(Auth)/login",
        "/(Auth)/register",
        "/(Dashboard)/dashboard",
        "/(Home)/"
      ]
    },
    "/(Auth)/forgot-password": {
      "filePath": "(Auth)/forgot-password.tsx"
    },
    "/(Auth)/login": {
      "filePath": "(Auth)/login.tsx"
    },
    "/(Auth)/register": {
      "filePath": "(Auth)/register.tsx"
    },
    "/(Dashboard)/dashboard": {
      "filePath": "(Dashboard)/dashboard.tsx"
    },
    "/(Home)/": {
      "filePath": "(Home)/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
